<a href="https://colab.research.google.com/github/Malu247/programacion1-/blob/main/parcial2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Nombre:** Maria Lucia Higuera Angarita
**Codigo:** 2260674

**PARTE II**

Instruccion 1

In [61]:
import numpy as np
np.random.seed(0)
datos = np.random.randint(153, 197, 50)

In [62]:
datos[datos > 180]

array([192, 189, 191, 192, 190, 188, 182, 192, 185, 185, 184, 188, 181,
       187])

In [63]:
funcion = lambda a, b: (b - a.mean())/a.std()

In [64]:
datos1 = funcion(datos, datos)
datos1

array([-1.56108372, -1.31511465, -1.31511465,  1.63651424, -0.8231765 ,
       -0.00327959,  0.16069979,  1.39054516,  0.32467918, -1.06914557,
        0.40666887,  0.40666887, -0.57720743, -1.47909403,  1.55452455,
        1.63651424,  0.32467918,  0.40666887, -0.16725897,  1.47253485,
        0.48865856, -0.49521773, -0.90516619, -0.8231765 ,  0.0787101 ,
       -0.24924866, -1.15113526, -0.33123835, -1.56108372, -0.08526928,
        1.30855547,  0.40666887,  0.81661732, -0.00327959, -0.00327959,
       -0.41322804,  1.63651424,  1.0625864 , -1.47909403, -0.8231765 ,
        1.0625864 ,  0.98059671, -0.74118681,  0.32467918,  1.30855547,
       -0.65919712,  0.73462763,  1.22656578, -1.56108372, -1.56108372])

In [65]:
import pandas as pd
datos2 = pd.DataFrame(datos1)
datos2

           0
0  -1.561084
1  -1.315115
2  -1.315115
3   1.636514
4  -0.823176
5  -0.003280
6   0.160700
7   1.390545
8   0.324679
9  -1.069146
10  0.406669
11  0.406669
12 -0.577207
13 -1.479094
14  1.554525
15  1.636514
16  0.324679
17  0.406669
18 -0.167259
19  1.472535
20  0.488659
21 -0.495218
22 -0.905166
23 -0.823176
24  0.078710
25 -0.249249
26 -1.151135
27 -0.331238
28 -1.561084
29 -0.085269
30  1.308555
31  0.406669
32  0.816617
33 -0.003280
34 -0.003280
35 -0.413228
36  1.636514
37  1.062586
38 -1.479094
39 -0.823176
40  1.062586
41  0.980597
42 -0.741187
43  0.324679
44  1.308555
45 -0.659197
46  0.734628
47  1.226566
48 -1.561084
49 -1.561084

In [84]:
e = datos2.describe()
e

                  0
count  5.000000e+01
mean   6.394885e-16
std    1.010153e+00
min   -1.561084e+00
25%   -8.231765e-01
50%   -3.279588e-03
75%    7.961199e-01
max    1.636514e+00

In [54]:
import pandas as pd
datos3 = pd.DataFrame(datos)
datos3

      0
0   153
1   156
2   156
3   192
4   162
5   172
6   174
7   189
8   176
9   159
10  177
11  177
12  165
13  154
14  191
15  192
16  176
17  177
18  170
19  190
20  178
21  166
22  161
23  162
24  173
25  169
26  158
27  168
28  153
29  171
30  188
31  177
32  182
33  172
34  172
35  167
36  192
37  185
38  154
39  162
40  185
41  184
42  163
43  176
44  188
45  164
46  181
47  187
48  153
49  153

In [70]:
from google.colab import files
import csv
resultados = [[datos]]

with open("resultados.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(resultados)

files.download("resultados.csv")

Instruccion 2

In [21]:
dic = {"Nombre": ["Niall","Harry","Louis","Zayn","Liam"], "Edad": [17,16,19,17,18], "Pais":["Irlanda","Inglaterra","Colombia","Afganistan","Japon"], "Calificacion":[7,8,6,3,10]}

In [32]:
tabla = pd.DataFrame(dic)
tabla

  Nombre  Edad        Pais  Calificacion
0  Niall    17     Irlanda             7
1  Harry    16  Inglaterra             8
2  Louis    19    Colombia             6
3   Zayn    17  Afganistan             3
4   Liam    18       Japon            10

In [31]:
tabla.head(2)

  Nombre  Edad        Pais  Calificacion
0  Niall    17     Irlanda             7
1  Harry    16  Inglaterra             8

In [37]:
tabla["Edad"]

0    17
1    16
2    19
3    17
4    18
Name: Edad, dtype: int64

In [38]:
tabla.loc[tabla["Edad"]>17]

  Nombre  Edad      Pais  Calificacion
2  Louis    19  Colombia             6
4   Liam    18     Japon            10

In [130]:

tabla.add({"a":[1,2,3,4,5], "b":[6,7,8,9,10],"c":[11,12,13,14,15],"f":[1,2,3,4,5]})

  Nombre Edad Pais Calificacion
0    NaN  NaN  NaN          NaN
1    NaN  NaN  NaN          NaN
2    NaN  NaN  NaN          NaN
3    NaN  NaN  NaN          NaN
4    NaN  NaN  NaN          NaN

In [45]:
grupo = tabla.groupby("Pais")["Calificacion"].mean()
grupo

Pais
Afganistan     3.0
Colombia       6.0
Inglaterra     8.0
Irlanda        7.0
Japon         10.0
Name: Calificacion, dtype: float64

In [72]:
from google.colab import files
import csv
datos_procesados = [[grupo]]

with open("datos_procesados.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(datos_procesados)

files.download("datos_procesados.csv")

**PARTE III**

In [47]:
prueba_a = np.random.gamma(shape=306, scale=0.0229, size=57)
prueba_b = np.random.normal(loc=7.2, scale=0.4, size=57)

In [48]:
df = pd.DataFrame({"A": prueba_a, "B": prueba_b})
df

           A         B
0   6.652624  7.095458
1   6.824034  7.190608
2   6.954703  7.235769
3   7.369360  6.962269
4   6.596903  7.157721
5   7.192699  7.497118
6   6.376488  6.898007
7   7.403442  7.144687
8   7.045894  6.350032
9   7.138931  6.787992
10  6.327868  6.993019
11  7.684932  7.143280
12  7.517586  6.689408
13  6.541510  7.792605
14  7.057610  7.863711
15  7.160546  7.200056
16  7.010530  7.802335
17  7.431057  7.241808
18  6.982120  7.105583
19  6.855331  7.527774
20  7.813874  7.361143
21  6.920624  6.624703
22  7.132938  7.308500
23  6.440500  6.923759
24  6.910451  6.927387
25  6.832883  6.595108
26  7.407746  8.078756
27  7.173761  7.616470
28  6.518530  7.186706
29  7.077729  7.226257
30  7.718577  7.306314
31  7.240130  7.660737
32  6.770539  7.255217
33  7.586755  7.140878
34  7.129508  7.873531
35  7.283943  7.588733
36  7.118899  7.843070
37  6.830875  7.097149
38  6.676191  7.923927
39  6.568632  7.556939
40  7.173761  7.161370
41  7.862780  7.049137
42  6.804469  6.997881
43  7.973691  6.654932
44  6.676236  7.653251
45  6.418742  6.919724
46  7.293807  6.492661
47  6.214230  7.336167
48  6.576297  7.491697
49  6.725796  6.764658
50  6.104795  6.048889
51  7.686598  6.935409
52  7.501805  7.482371
53  6.955646  7.056561
54  6.502181  7.492793
55  7.012501  7.185453
56  6.583135  7.435566

In [49]:
df.describe()

               A          B
count  57.000000  57.000000
mean    7.006030   7.209352
std     0.436666   0.412709
min     6.104795   6.048889
25%     6.676191   6.962269
50%     7.010530   7.186706
75%     7.283943   7.492793
max     7.973691   8.078756

La calificacion promedio del grupo B es un 0.2 mas alta que la de grupo A, pero este grupo tiene una desviacion estandar un 0.03 mas alta que el B. La calificacion minima del grupo A es aproximadamente 0.1 mas alta y la calificacion maxima es aproximadamente 0.1 mas baja en comparacion con el grupo B. El 25% de los estudiantes del grupo B tienen una calificacion promedio de 6.9 mientras que la calificacion promedio del grupo B es de 6.6. El 75% de los estudiantes tienen una calificacion promedio de 7.2 en el grupo A y 7.4 en el grupo B.

In [74]:
from scipy import stats
from scipy.stats import shapiro

In [78]:
p1 = shapiro(df["A"])
p2= shapiro(df["B"])

In [79]:
p1

ShapiroResult(statistic=np.float64(0.9877683880874226), pvalue=np.float64(0.8327843849986929))

Como el valor p es mayor a 0.05 (0.83>0.05) , no se rechaza la hipotesis de normalidad con una confianza de 95%.

In [80]:
p2

ShapiroResult(statistic=np.float64(0.9865773047701507), pvalue=np.float64(0.7780217514592187))

Como el valor p es mayor a 0.05 (0.77>0.05), no se rechaza la hipotesis de normalidad con una confianza de 95%.

In [82]:
valor = stats.ttest_rel(df["A"], df["B"])
valor

TtestResult(statistic=np.float64(-2.6130649771835164), pvalue=np.float64(0.011501527206102497), df=np.int64(56))

Se rechaza que el puntaje medio de el puntaje medio en ambas encuestas es igual con una confianza del 95% porque el valor p es menor a 0.05 (0.01<0.05)

In [85]:
relacion = stats.kendalltau(df["A"], df["B"])
relacion

SignificanceResult(statistic=np.float64(0.02380952380952381), pvalue=np.float64(0.7936404388893481))

No se rechaza con una confianza del 95% que los puntajes de ambas encuestas no están correlacionados porque el valor p es mayor a 0.05

In [86]:
spearman = stats.spearmanr(df["A"], df["B"])
spearman

SignificanceResult(statistic=np.float64(0.036232823437905105), pvalue=np.float64(0.7890232206282706))

No se rechaza con una confianza del 95% que los puntajes de ambas encuestas no están correlacionados porque el valor p es mayor a 0.05

In [88]:
import os
os.makedirs("comparacion", exist_ok=True)

In [137]:
%%writefile comparacion/pruebat.py
import numpy as np
import pandas as pd
from scipy import stats
from scipy.stats import shapiro
def prueba_t():
  Prueba_A = df1[1]
  Prueba_B = df1[2]
    p1 = shapiro()
    p2= shapiro()
    valor = stats.ttest_rel(df1["Prueba_A"], df1["Prueba_B"])
    print("Shapiro A", p1)
    print("Shapiro B", p2)

Overwriting comparacion/pruebat.py

In [103]:
%%writefile comparacion/cor.py
import numpy as np
import pandas as pd
from scipy import stats
from scipy.stats import shapiro
def cor(df1):
    relacion = stats.kendalltau(df1["Prueba_A"], df1["Prueba_B"])
    spearman = stats.spearmanr(df1["Prueba_A"], df1["Prueba_B"])
    print("Kendall", relacion)
    print("Spearman", spearman)

Overwriting comparacion/cor.py

In [104]:
df1 = pd.DataFrame({
 "Estudiante": range(1, 11),
 "Prueba_A": [7.1, 7.5, 6.8, 7.3, 7.0, 7.4, 6.9, 7.2, 7.6, 7.1],
 "Prueba_B": [6.9, 7.2, 7.0, 7.1, 6.8, 7.3, 7.0, 7.1, 7.4, 7.0]
})

In [142]:
df1

   Estudiante  Prueba_A  Prueba_B
0           1       7.1       6.9
1           2       7.5       7.2
2           3       6.8       7.0
3           4       7.3       7.1
4           5       7.0       6.8
5           6       7.4       7.3
6           7       6.9       7.0
7           8       7.2       7.1
8           9       7.6       7.4
9          10       7.1       7.0

In [131]:
import comparacion
from comparacion import pruebat
from comparacion import cor

In [140]:
comparacion.pruebat()

TypeError: 'module' object is not callable

In [141]:
comparacion.cor()

TypeError: 'module' object is not callable